/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meupaint;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author bv110309
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private int xPress;
    private int yPress;
    
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        painelDesenho = new meupaint.PainelDesenho();
        painelBotoes = new javax.swing.JPanel();
        btnLinha = new javax.swing.JToggleButton();
        btnRetangulo = new javax.swing.JToggleButton();
        btnElipse = new javax.swing.JToggleButton();
        btnCor1 = new javax.swing.JButton();
        btnCor2 = new javax.swing.JButton();
        txtLados = new javax.swing.JTextField();
        btnPoligono = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu Paint");

        painelDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseDragged(evt);
            }
        });
        painelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelDesenhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );

        buttonGroup.add(btnLinha);
        btnLinha.setSelected(true);
        btnLinha.setText("Linha");
        btnLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinhaActionPerformed(evt);
            }
        });

        buttonGroup.add(btnRetangulo);
        btnRetangulo.setText("Retângulo");
        btnRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetanguloActionPerformed(evt);
            }
        });

        buttonGroup.add(btnElipse);
        btnElipse.setText("Elipse");

        btnCor1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCor1.setText("Cor 1");
        btnCor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCor1ActionPerformed(evt);
            }
        });

        btnCor2.setBackground(new java.awt.Color(204, 204, 204));
        btnCor2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCor2.setForeground(new java.awt.Color(255, 255, 255));
        btnCor2.setText("Cor 2");
        btnCor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCor2ActionPerformed(evt);
            }
        });

        txtLados.setText("3");
        txtLados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadosActionPerformed(evt);
            }
        });

        buttonGroup.add(btnPoligono);
        btnPoligono.setText("Poligono");
        btnPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoligonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnElipse, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLados, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCor1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCor2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLinha)
                    .addComponent(btnRetangulo)
                    .addComponent(btnElipse)
                    .addComponent(btnCor1)
                    .addComponent(btnCor2)
                    .addComponent(txtLados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPoligono))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void painelDesenhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMousePressed
        xPress = evt.getX();
        yPress = evt.getY();
        
    }//GEN-LAST:event_painelDesenhoMousePressed

    private void painelDesenhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseReleased
        
        Forma novaForma = null;
        
        if ( btnLinha.isSelected() ) {
            novaForma = new Linha( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground() );
        } else if ( btnRetangulo.isSelected() ) {
            novaForma = new Retangulo( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground(), btnCor2.getForeground() );
        } else if ( btnElipse.isSelected() ){
            novaForma = new Elipse( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground(), btnCor2.getForeground() );
        } else if (btnPoligono.isSelected()) {
            int lados = Integer.parseInt(txtLados.getText()); 
            novaForma = new Poligono(xPress, yPress, evt.getX(), evt.getY(), lados, btnCor1.getForeground(), btnCor2.getForeground());
        }
        
        painelDesenho.adicionarForma( novaForma );
        painelDesenho.setFormaTemporaria( null );
        painelDesenho.repaint();
        
    }//GEN-LAST:event_painelDesenhoMouseReleased

    private void painelDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseDragged
        
        Forma formaTemp = null;
        
        if ( btnLinha.isSelected() ) {
            formaTemp = new Linha( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground() );
        } else if ( btnRetangulo.isSelected() ) {
            formaTemp = new Retangulo( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground(), btnCor2.getForeground() );
        } else if (btnElipse.isSelected() ){
            formaTemp = new Elipse( xPress, yPress, evt.getX(), evt.getY(), btnCor1.getForeground(), btnCor2.getForeground() );
        } else if (btnPoligono.isSelected()) {
            int lados = Integer.parseInt(txtLados.getText()); // Número de lados do polígono a partir de um campo de texto
            formaTemp = new Poligono(xPress, yPress, evt.getX(), evt.getY(), lados, btnCor1.getForeground(), btnCor2.getForeground());
        }
        
        painelDesenho.setFormaTemporaria( formaTemp );
        painelDesenho.repaint();
        
    }//GEN-LAST:event_painelDesenhoMouseDragged

    private void btnCor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCor1ActionPerformed
        
        Color c = JColorChooser.showDialog( 
                this, "Cor do Contorno", btnCor1.getForeground() );
        
        if ( c != null ) {
            btnCor1.setForeground( c );
        }
        
    }//GEN-LAST:event_btnCor1ActionPerformed

    private void btnCor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCor2ActionPerformed
        
        Color c = JColorChooser.showDialog( 
                this, "Cor do Contorno", btnCor2.getForeground() );
        
        if ( c != null ) {
            btnCor2.setForeground( c );
        }
        
    }//GEN-LAST:event_btnCor2ActionPerformed

    private void btnRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetanguloActionPerformed

    private void txtLadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLadosActionPerformed

    private void btnLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinhaActionPerformed
    }//GEN-LAST:event_btnLinhaActionPerformed

    private void btnPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoligonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoligonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCor1;
    private javax.swing.JButton btnCor2;
    private javax.swing.JToggleButton btnElipse;
    private javax.swing.JToggleButton btnLinha;
    private javax.swing.JToggleButton btnPoligono;
    private javax.swing.JToggleButton btnRetangulo;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel painelBotoes;
    private meupaint.PainelDesenho painelDesenho;
    private javax.swing.JTextField txtLados;
    // End of variables declaration//GEN-END:variables
}
